<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>ForumApp.DTOs</AssemblyName>
		<RootNamespace>ForumApp.DTOs</RootNamespace>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>bin\Debug\net8.0\MyProject.xml</DocumentationFile>
	</PropertyGroup>

</Project>
